FROM amazonlinux:2

RUN yum update -y && yum install -y \
    wget \
    gcc \
    glibc \
    glibc-common \
    gd \
    gd-devel \
    openssl \
    openssl-devel \
    httpd \
    php \
    php-gd \
    unzip

RUN wget -O /tmp/nagioscore.tar.gz https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz \
    && cd /tmp && tar xzf nagioscore.tar.gz \
    && cd /tmp/nagios-4.4.6 \
    && ./configure --with-httpd-conf=/etc/httpd/conf.d/ \
    && make all \
    && make install-groups-users \
    && usermod -a -G nagios apache \
    && make install \
    && make install-daemoninit \
    && make install-commandmode \
    && make install-config \
    && make install-webconf

RUN echo "ServerName localhost" >> /etc/httpd/conf/httpd.conf

COPY nagios-init.sh /etc/init.d/nagios
RUN chmod +x /etc/init.d/nagios \
    && chkconfig --add nagios

EXPOSE 80

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]